@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 06 15:54:58 -0700 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Reversible_OR_gate_Tb_behav -key {Behavioral:sim_1:Functional:Reversible_OR_gate_Tb} -tclbatch Reversible_OR_gate_Tb.tcl -log simulate.log"
call xsim  Reversible_OR_gate_Tb_behav -key {Behavioral:sim_1:Functional:Reversible_OR_gate_Tb} -tclbatch Reversible_OR_gate_Tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
